server:
  port: 9900

zuul:
  proxy:
    route:
      account-service: /a
      doge-service: /d

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri}/eureka/
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
