server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    
eureka:
  instance:
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  platform:
    config:
      server:
        uri: https://github.com/joshlong/microservice-webinar-configuration
        basedir: target/config

