server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'

spring:
  cloud:
    config:
      server:
        uri: https://github.com/joshlong/spring-doge-microservice-configuration


---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://eureka-service.${application.domain}}/v2/
  instance:
    hostname: ${application.domain}
    nonSecurePort: 80
