server:
  port: ${vcap.application.port:8888}

#config-dir: ${user.home}/Desktop/bootiful-microservices/code/spring-doge-microservice-configuration

spring:
  cloud:
    config:
      server:
        uri: ${CONFIG_DIR:https://github.com/joshlong/spring-doge-microservice-configuration}


